[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "sober"
version = "0.4.1"
description = "sober optimises built environment robustly"
readme = "README.md"
license = "BSD-3-Clause"
authors = [{ name = "Cheng Cui", email = "cheng.cui.95@gmail.com" }]
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
]
dependencies = [
    "eppy~=0.5.63",
    "numpy~=2.4",
    "psutil==7.*",
    # pymoo 0.6.2 uses moocore for non-dominated sorting but only requires moocore>=0.1.7
    # moocore 0.3.1 can crash on duplicate individuals, which was fixed in 0.3.2: multi-objective/moocore#74
    "pymoo==0.6.1.*",
    "scipy~=1.17",
]

[project.urls]
repository = "https://github.com/airallergy/sober"
documentation = "https://airallergy.github.io/sober/"

[dependency-groups]
dev = [
    "mkdocs-material~=9.7",
    "mkdocstrings-python==2.*",
    "mkdocstrings[python]==1.*",
    "mypy==2.3.*",
    "pytest~=9.1",
    "pytest-cov~=7.1",
    "ruff==0.16.*",
]

[tool.uv]
required-version = "==0.12.*"

[tool.ruff.format]
line-ending = "lf"
skip-magic-trailing-comma = true

[tool.ruff.lint]
select = [
    "B",
    "C4",
    "D",
    "E",
    "F",
    "FLY",
    "FURB",
    "I",
    "ISC",
    "LOG",
    "N",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PYI",
    "RET",
    "RUF",
    "SIM",
    "SLOT",
    "T20",
    "TC",
    "TID",
    "TRY",
    "UP",
    "YTT",
]
# consider removing:
#   - E501: long line
#   - PLR0912: too many branches
#   - PLR2004: magic number
#   - PLW0603: use global
#   - TRY003: long raise message
ignore = [
    "E266",
    "E501",
    "E741",
    "PLR0912",
    "PLR0913",
    "PLR0917",
    "PLR2004",
    "PLW0603",
    "RET505",
    "RUF023",
    "TRY003",
    "UP046",   # TODO: suppress for now
    "UP047",   # TODO: suppress for now
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
files = ["sober", "tests"]
namespace_packages = false
ignore_missing_imports = true
strict = true
enable_incomplete_feature = ["PreciseTupleTypes"]

[tool.pytest.ini_options]
addopts = "--cov=sober"
testpaths = ["tests"]
