name: Publish Docs

on:
  push:
    branches: main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.*"
          enable-cache: true
          cache-dependency-glob: uv.lock
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: uv sync --all-extras --all-groups
      - run: uv run mkdocs build --strict
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
