name: Publish PyPI

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.12"
      - run: |
          python -m pip install build
          python -m build
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: python-package-distributions
          path: dist/

  upload-testpypi:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/sober
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8.0.1
        with:
          name: python-package-distributions
          path: dist/
      - uses: pypa/gh-action-pypi-publish@v1.14.2
        with:
          repository-url: https://test.pypi.org/legacy/

  upload-pypi:
    needs: upload-testpypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sober
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8.0.1
        with:
          name: python-package-distributions
          path: dist/
      - uses: pypa/gh-action-pypi-publish@v1.14.2
