name: Test

on:
  workflow_dispatch:
  push:
    branches: main
    tags: "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.*"
          enable-cache: true
          cache-dependency-glob: uv.lock
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync --all-extras --all-groups
      - run: uv run ruff format --diff
      - run: uv run ruff check --diff
      - run: uv run mypy
      - run: uv run pytest
